### PR TITLE
Development

### PR DESCRIPTION
**Pull request by phh**
Logic for mapped fields - how to extend this functionality can be found in productsearch: https://github.com/BenjaminMedia/product-search/blob/development/htdocs/content/themes/product-search/resources/admin/trapp.php

This is to expected the last PR in terms of logic (unless some bugs are found). I'm currently working on the readme file in terms of how to extend / add mapping fields.

### CODE REVIEW

**Comment by phh** [comment]
Okay let me just finish the readme and some other minor fixes

**Comment by phh** [comment]
Updated and ready :)

**Comment by jonastanz** [comment]
Hi. We think in general that avoiding the "continue"-keyword in simple situations makes the code easier to read.

E.g. change:

foreach ($translations as $slug => $translation) {
    if ($translation == $this->postId) {
        continue;
    }
    $trapp_meta = get_post_meta($translation, self::TRAPP_META_KEY, true);
    if (!$trapp_meta) {
        continue;
    }
    delete_post_meta($translation, self::TRAPP_META_KEY);
    delete_post_meta($translation, self::TRAPP_META_LINK);
}

to:

foreach ($translations as $slug => $translation) {
    if ($translation != $this->postId) {

        $trapp_meta = get_post_meta($translation, self::TRAPP_META_KEY, true);

        if ($trapp_meta) {
            delete_post_meta($translation, self::TRAPP_META_KEY);
            delete_post_meta($translation, self::TRAPP_META_LINK);
        }

    }
}

**Comment by jonastanz** [comment]
Hi. We think in general that avoiding the "continue"-keyword in simple situations makes the code easier to read.

E.g. change:

foreach ($translations as $slug => $translation) {
	if ($translation == $this->postId) {
		continue;
	}
	$trapp_meta = get_post_meta($translation, self::TRAPP_META_KEY, true);
	if (!$trapp_meta) {
		continue;
	}
	delete_post_meta($translation, self::TRAPP_META_KEY);
	delete_post_meta($translation, self::TRAPP_META_LINK);
}

to:

foreach ($translations as $slug => $translation) {
	if ($translation != $this->postId) {
		$trapp_meta = get_post_meta($translation, self::TRAPP_META_KEY, true);
		if ($trapp_meta) {
			delete_post_meta($translation, self::TRAPP_META_KEY);
			delete_post_meta($translation, self::TRAPP_META_LINK);
		}
	}
}

**Comment by jonastanz** [comment]
Hi. We think in general that avoiding the "continue"-keyword in simple situations makes the code easier to read.

E.g. change:

foreach ($translations as $slug => $translation) {
  if ($translation == $this->postId) {
    continue;
  }
  $trapp_meta = get_post_meta($translation, self::TRAPP_META_KEY, true);
  if (!$trapp_meta) {
    continue;
  }
  delete_post_meta($translation, self::TRAPP_META_KEY);
  delete_post_meta($translation, self::TRAPP_META_LINK);
}

to:

foreach ($translations as $slug => $translation) {
  if ($translation != $this->postId) {

    $trapp_meta = get_post_meta($translation, self::TRAPP_META_KEY, true);

    if ($trapp_meta) {
      delete_post_meta($translation, self::TRAPP_META_KEY);
      delete_post_meta($translation, self::TRAPP_META_LINK);
    }

  }
}

**Pull request merged**
